// Bundles each edge function and its local stage-runner dependencies into one
// ESM file. InsForge deploy uploads one file, while generation-worker imports
// the same runners used by the authenticated compatibility endpoints.
//
// Usage: node functions/build.mjs            (build all)
//        node functions/build.mjs view hero  (build a subset)
import { mkdirSync, readdirSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { build } from 'esbuild';

const dir = dirname(fileURLToPath(import.meta.url));
const distDir = join(dir, 'dist');
mkdirSync(distDir, { recursive: true });

const sourceSlugs = readdirSync(dir)
  .filter((f) => f.endsWith('.ts') && !f.startsWith('_'))
  .map((f) => f.replace(/\.ts$/, ''));

for (const file of readdirSync(distDir).filter((f) => f.endsWith('.ts'))) {
  if (!sourceSlugs.includes(file.replace(/\.ts$/, ''))) {
    rmSync(join(distDir, file));
    console.log(`removed orphaned dist/${file}`);
  }
}

const only = process.argv.slice(2);
const slugs = sourceSlugs
  .filter((s) => only.length === 0 || only.includes(s));

for (const slug of slugs) {
  await build({
    entryPoints: [join(dir, `${slug}.ts`)],
    outfile: join(distDir, `${slug}.ts`),
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    treeShaking: true,
    external: ['npm:*'],
    banner: {
      js: '// Generated by functions/build.mjs. Do not edit directly.',
    },
    logLevel: 'silent',
  });
  console.log(`built dist/${slug}.ts`);
}
