-- Posterlytics schema 16 — scenario discriminator + event details
--
-- Generalizes a campaign from the single "product URL → poster" scenario to
-- MULTIPLE scenarios. The first added scenario is 'event' (a Luma event); more
-- may follow. Mirrors the db/09 (poster_style) / db/13 pattern: additive,
-- IF NOT EXISTS, and NO CHECK constraint so future scenarios never require a
-- migration.
--
-- `scenario`      : which kind of thing this campaign promotes.
--                     'product' (default) — a product with a website (today's flow)
--                     'event'             — a Luma event (luma.com/<slug>)
--                   The whole tracking half (placements/scans/conversions + RPCs +
--                   view/convert/scan-geo) is scenario-agnostic and unchanged; only
--                   the content agents (analyze/hero/landing) branch on this.
--
-- `event_details` : nullable JSONB bag for the event scenario (NULL for products).
--                   All fields optional so partial Luma scrapes round-trip (e.g. a
--                   "Register to See Address" event exposes city but not street).
--                   Shape mirrors `EventDetails` in src/lib/types.ts:
--                     event_name, starts_at (ISO-8601 w/ tz offset), ends_at,
--                     tz_offset, tz_label,
--                     location_name, location_address, location_city,
--                     location_region, location_country,
--                     attendance_mode ('offline'|'online'), online_platform,
--                     address_hidden (bool),
--                     host_name, host_url, host_logo_url, hosts (text[]),
--                     price_label, register_url,
--                     cover_image_url, cover_image_key   (Flow A / Phase 2)
--                   For events, product_url is repurposed as the event URL,
--                   product_name as the event title, destination_url as the Luma
--                   RSVP target; event_details.event_name is the canonical title.
--
-- Purely additive: every existing row defaults scenario='product' with a NULL
-- event_details, so nothing about the product flow changes.
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS scenario TEXT NOT NULL DEFAULT 'product';
ALTER TABLE campaigns ADD COLUMN IF NOT EXISTS event_details JSONB;
